language: java
jdk:
  - openjdk6

#I want to run the integration tests which require a browser. I will have to look into
# travis-ci's options.  at minimum I'll figure out how to run phantom-js#
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

#default script is....  script: mvn test
script: mvn test integration-test